### ISSUE TITLE
Could I change this code for CMS player?

### ISSUE THREAD

**Issue by photonrain** [brendonmay/brendonmay.github.io#22]
Hello, I am CMS player. I happen to know these excellent pages, which really impress me. I want to change the code for CMS player, because there is no good calculation tool for us.
In CMS, the StarForce is quite different from other servers. There are also some CMS unique contents, such as familiar card and damage limit break stone system.
Unfortunately, I didn't find the license for this project, so I can't easily change this code. If I use your code or I write new code base on yours, I will indicate the sources and add the link.
I am looking forward to your reply.
Thank you!
:)

**Comment by brendonmay** [comment]
Not a problem, feel free to fork it!
