### ISSUE TITLE
Inconsistency between legion and hyper stat optimizers

### ISSUE THREAD

**Issue by NotTsunami** [brendonmay/brendonmay.github.io#27]
The standalone hyper stat optimizer allows you to select a mobbing or bossing focus, but the legion optimizer does not.

**Comment by brendonmay** [comment]
I do not intend on adding this to the legion calculator. I would suggest people use the hyperstat calculator, then xenogents tool to create the legion board of their choosing (as to whether they want to prioritize bonus exp over damage).

If anyone wants to integrate it into the legion tool, they are welcome to and I can look over the code and merge to master.
