### ISSUE TITLE
Hyperstat calculator out of date with decimal ied now being shown

### ISSUE THREAD

**Issue by sethhuieldar** [brendonmay/brendonmay.github.io#34]
The ied field on the hyper stat calculator still seems to assume ied is shown as a whole number in the stat window, which is no longer true. Putting in the decimal stat as now shown in the window causes the calculator to not use your class' additional ied sources which seems to not be how a user would expect it to work.

**Comment by sethhuieldar** [comment]
Seems to be the case on the WSE and Legion calculator too

**Comment by brendonmay** [comment]
Fixed
