### ISSUE TITLE
Star Force Star Catching is 5% multiplicative

### ISSUE THREAD

**Issue by LoneFireBlossom** [brendonmay/brendonmay.github.io#46]
not 4.5%

see:

https://strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catcher
https://maplestory.nexon.com/Guide/ProbabilityResult/MonthData
http://gamebulletin.nexon.com/maplestory/inspection3.html?ReturnUrl=%2fNews%2fNotice%2fNotice%2f133192

Thank you for your calculator, It helps me a lot :)

**Comment by brendonmay** [comment]
Fixed

**Comment by CuteReimu** [comment]
Really? But I saw it was still 4.5% in https://strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catching
![image](https://github.com/brendonmay/brendonmay.github.io/assets/77955264/b4209848-7fbd-412e-83c0-45d0b5b3d77c)

**Comment by LoneFireBlossom** [comment]
> Really? But I saw it was still 4.5% in [strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catching](https://strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catching) ![image](https://user-images.githubusercontent.com/77955264/283001592-b4209848-7fbd-412e-83c0-45d0b5b3d77c.png)
> 
> > Before each attempt, you will play a Star Catching minigame where a star moves side to side starting from the left. Click the "Stop" button or press Spacebar to stop the star. If it lands on the yellow region, **the success rate will increase by 4.5% multiplicatively.** Maintain/Decrease and Destroy rates will be redistributed at the same bracketed rates.

When I open this issue it says 5%...😂

https://strategywiki.org/w/index.php?title=MapleStory/Spell_Trace_and_Star_Force&oldid=1028611#Star_Catcher

<img width="1077" alt="image" src="https://github.com/brendonmay/brendonmay.github.io/assets/50087596/d99fd8e2-3390-42c5-9708-0c6f1f69b545">

**Comment by CuteReimu** [comment]
> > Really? But I saw it was still 4.5% in [strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catching](https://strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catching) ![image](https://user-images.githubusercontent.com/77955264/283001592-b4209848-7fbd-412e-83c0-45d0b5b3d77c.png)
> > > Before each attempt, you will play a Star Catching minigame where a star moves side to side starting from the left. Click the "Stop" button or press Spacebar to stop the star. If it lands on the yellow region, **the success rate will increase by 4.5% multiplicatively.** Maintain/Decrease and Destroy rates will be redistributed at the same bracketed rates.
> 
> When I opened this issue the wiki said that the probability was 5%...😂
> 
> https://strategywiki.org/w/index.php?title=MapleStory/Spell_Trace_and_Star_Force&oldid=1028611#Star_Catcher
> 
> <img alt="image" width="1077" src="https://user-images.githubusercontent.com/50087596/283002636-d99fd8e2-3390-42c5-9708-0c6f1f69b545.png">

I think you are browsing an old revision.

![image](https://github.com/brendonmay/brendonmay.github.io/assets/77955264/877c9796-a6c0-4f3b-8b3f-837f61e59a94)

**Comment by CuteReimu** [comment]
@brendonmay Maybe you should change it to 4.5% again...

**Comment by LoneFireBlossom** [comment]
> > > Really? But I saw it was still 4.5% in [strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catching](https://strategywiki.org/wiki/MapleStory/Spell_Trace_and_Star_Force#Star_Catching) ![image](https://user-images.githubusercontent.com/77955264/283001592-b4209848-7fbd-412e-83c0-45d0b5b3d77c.png)
> > > > Before each attempt, you will play a Star Catching minigame where a star moves side to side starting from the left. Click the "Stop" button or press Spacebar to stop the star. If it lands on the yellow region, **the success rate will increase by 4.5% multiplicatively.** Maintain/Decrease and Destroy rates will be redistributed at the same bracketed rates.
> > 
> > 
> > When I opened this issue the wiki said that the probability was 5%...😂
> > [strategywiki.org/w/index.php?title=MapleStory/Spell_Trace_and_Star_Force&oldid=1028611#Star_Catcher](https://strategywiki.org/w/index.php?title=MapleStory/Spell_Trace_and_Star_Force&oldid=1028611#Star_Catcher)
> > <img alt="image" width="1077" src="https://user-images.githubusercontent.com/50087596/283002636-d99fd8e2-3390-42c5-9708-0c6f1f69b545.png">
> 
> I think that's an old revision.
> 
> ![image](https://user-images.githubusercontent.com/77955264/283003039-877c9796-a6c0-4f3b-8b3f-837f61e59a94.png)

**When I opened this issue** the wiki said that the probability was 5%...
**When I opened this issue** the wiki said that the probability was 5%...
**When I opened this issue** the wiki said that the probability was 5%...
**When I opened this issue** the wiki said that the probability was 5%...
**When I opened this issue** the wiki said that the probability was 5%...

**Comment by LoneFireBlossom** [comment]
https://maplestory.nexon.com/News/Notice/Notice/133192

Star Force reinforcement is periodically verified based on usage logs, and when checked with statistics, it was confirmed that it is operating without much difference from the probabilities announced in the game . You can checkthisStar Forceattempted in the second half of 2020 below . This is the result excluding5, 10, and 15star 100% success eventswithsuccesschance timeattempts, andsuperiorenhancements , and the total attempts and resultsare calculatedwhenstar catchis successful / failed with the anti-destruction option disabled.This is a probability table . **When a star catchis successful, the success probabilityis 1.05 times the original probability .** (Based onstars, the success rate ofstar catch is 31.5%, the rate of maintaining the level is 66.45% , and the destruction rateis 2.06% .)              


Official announced probability is 5%

**Comment by CuteReimu** [comment]
I found another place where 4.5% appeared in the code.

https://github.com/brendonmay/brendonmay.github.io/blob/02754ce21a945993548e0e323477f08dc0b77bdf/starforceCalculator/index.html#L86-L90
