### ISSUE TITLE
Inner Ability

### ISSUE THREAD

**Issue by RXUsagi** [brendonmay/brendonmay.github.io#55]
Inner Ability
it use less honor exp when I aim for L1 + L3 instead of L3 + L1 N/A
Current Inner Ability
L1 - N/A , L2 - Buff duration 38%, L3 - N/A
Desired Inner Ability
L1 - Attack Speed +1, L2 - Buff duration 38%, L3 - Boss damage 10%
You are expected to use between: 4,028,044 and 19,410,502 Honor Exp Median: 13,762,420 Honor Exp

Compare to
Current Inner Ability
L1 - N/A , L2 - Buff duration 38%, L3 - N/A
Desired Inner Ability
L1 - N/A , L2 - Buff duration 38%, L3 - Boss damage 10%
You are expected to use between: 10,951,961 and 52,775,766 Honor Exp Median: 26,387,883 Honor Exp

[uncheck] Use Only Honor
[uncheck] Use Chaos Circulators
[check] 50% Inner Ability Event

**Comment by brendonmay** [comment]
The issue has been resolved. Please let me know if you find any other issues @RXUsagi
