### ISSUE TITLE
30% Off Starforce Calculation

### ISSUE THREAD

**Issue by bowenzheng98** [brendonmay/brendonmay.github.io#6]
Refering to this video (at the timestamp linked): https://youtu.be/rI5zEkE7Y8s?t=634; Nox shows that during 30% off starforce event for GMS, the applied discount is only 15% when safeguarding

In this file: [https://github.com/brendonmay/brendonmay.github.io/blob/master/starforceCalculator/main.js](url)

At line 128: `if (thirty_off) {multiplier = multiplier - 0.3;}`

Is there a potential issue here where the attempt cost may be incorrect?

**Comment by brendonmay** [comment]
The way I have coded this is correct. Discount percentages are additive, not multiplicative. One way to think about it is
Event is -30%, Safeguard is +100%, so you're paying 170% total.
